<h1>6. Consider any sales training/ weather forecasting dataset</h1>
<hr>
<strong>a. Compute mean of a series grouped by another series</strong></br>
<strong>b. Fill an intermittent time series to replace all missing dates with values of previous non-missing date.</strong></br>
<strong>c. Perform appropriate year-month string to dates conversion.</strong></br>
<strong>d. Split a dataset to group by two columns and then sort the aggregated results within the groups.</strong></br>
<strong>e. Split a given dataframe into groups with bin counts.</strong></br>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ls

Datasets/           Prac3.ipynb         Prac8 - Sheet1.csv  delete.pdf
PDFS/               Prac4.ipynb         Prac8.ipynb         prac7.csv
PYQ_Q2.csv          Prac5.ipynb         Prac_4_Sheet.csv
PYQ_Q4.csv          Prac6.ipynb         Practicle_1.ipynb
Prac2.ipynb         Prac7.ipynb         delete.ipynb

In [3]:
df=pd.read_csv("/Users/jatin/Documents/DAV/Practicles/Datasets/weatherHistory.csv")

In [4]:
df.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [5]:
df=df.sample(frac=0.004)

In [6]:
df=df.drop(df[df['Summary'].isin(['Windy and Mostly Cloudy','Breezy and Foggy'])].index)

In [7]:
df['Summary'].value_counts()

Partly Cloudy               126
Mostly Cloudy                89
Overcast                     86
Clear                        46
Foggy                        32
Breezy and Overcast           3
Humid and Mostly Cloudy       1
Breezy and Partly Cloudy      1
Breezy                        1
Breezy and Mostly Cloudy      1
Name: Summary, dtype: int64

In [8]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
56603,2012-07-22 11:00:00.000 +0200,Partly Cloudy,rain,18.838889,18.838889,0.79,14.9247,7.0,11.4471,0.0,1018.90,Mostly cloudy throughout the day.
17554,2008-04-01 10:00:00.000 +0200,Mostly Cloudy,rain,10.022222,10.022222,0.58,14.3290,22.0,8.1305,0.0,1017.21,Mostly cloudy starting in the morning.
83563,2015-06-02 22:00:00.000 +0200,Partly Cloudy,rain,19.888889,19.888889,0.69,6.2951,120.0,16.1000,0.0,1019.80,Partly cloudy throughout the day.
40697,2010-03-29 18:00:00.000 +0200,Mostly Cloudy,rain,17.844444,17.844444,0.40,11.0446,183.0,9.9820,0.0,1013.11,Partly cloudy starting overnight continuing un...
48770,2011-06-30 02:00:00.000 +0200,Mostly Cloudy,rain,16.783333,16.783333,0.91,16.2288,300.0,14.1680,0.0,1010.16,Partly cloudy starting overnight.
...,...,...,...,...,...,...,...,...,...,...,...,...
34224,2009-10-04 00:00:00.000 +0200,Clear,rain,5.555556,5.555556,0.86,0.0000,0.0,16.1000,0.0,1017.90,Partly cloudy starting in the morning continui...
95975,2016-09-19 02:00:00.000 +0200,Overcast,rain,17.638889,17.638889,0.84,5.7960,16.0,15.1823,0.0,1008.55,Overcast throughout the day.
20490,2008-01-10 18:00:00.000 +0100,Foggy,snow,-2.244444,-2.244444,1.00,0.0000,0.0,0.0000,0.0,1028.57,Foggy until night.
49731,2011-05-11 04:00:00.000 +0200,Mostly Cloudy,rain,13.677778,13.677778,0.76,6.2790,29.0,15.8263,0.0,1020.28,Partly cloudy until evening.
36708,2010-12-15 12:00:00.000 +0100,Overcast,snow,-2.222222,-6.644444,0.88,12.7351,309.0,11.0768,0.0,1018.18,Foggy in the morning.

# a. Compute mean of a series grouped by another series

In [9]:
df.groupby(['Precip Type','Summary']).mean(numeric_only=1).drop('Loud Cover',axis=1)

                                      Temperature (C)  \
Precip Type Summary
rain        Breezy                           6.111111
            Breezy and Mostly Cloudy        22.222222
            Breezy and Overcast              9.662963
            Breezy and Partly Cloudy        21.111111
            Clear                           15.194577
            Foggy                            6.853216
            Humid and Mostly Cloudy         20.011111
            Mostly Cloudy                   13.737468
            Overcast                         9.570118
            Partly Cloudy                   17.745151
snow        Clear                           -5.283333
            Foggy                           -4.329915
            Mostly Cloudy                   -5.733333
            Overcast                        -2.819722
            Partly Cloudy                   -3.419841

                                      Apparent Temperature (C)  Humidity  \
Precip Type Summary
rain        Breezy                                    1.605556  0.600000
            Breezy and Mostly Cloudy                 22.222222  0.760000
            Breezy and Overcast                       6.981481  0.696667
            Breezy and Partly Cloudy                 21.111111  0.260000
            Clear                                    14.704497  0.753333
            Foggy                                     6.228363  0.960000
            Humid and Mostly Cloudy                  20.011111  0.870000
            Mostly Cloudy                            13.006460  0.719651
            Overcast                                  7.948653  0.838636
            Partly Cloudy                            17.413324  0.627119
snow        Clear                                    -7.855556  0.867500
            Foggy                                    -5.826923  0.928462
            Mostly Cloudy                            -9.791667  0.850000
            Overcast                                 -6.812222  0.888500
            Partly Cloudy                            -8.119841  0.741429

                                      Wind Speed (km/h)  \
Precip Type Summary
rain        Breezy                            28.980000
            Breezy and Mostly Cloudy          28.980000
            Breezy and Overcast               29.221500
            Breezy and Partly Cloudy          35.420000
            Clear                              6.699133
            Foggy                              5.131663
            Humid and Mostly Cloudy           12.155500
            Mostly Cloudy                     11.297707
            Overcast                          12.457253
            Partly Cloudy                     10.713868
snow        Clear                              7.486500
            Foggy                              4.634323
            Mostly Cloudy                      9.893450
            Overcast                          12.366410
            Partly Cloudy                     12.983500

                                      Wind Bearing (degrees)  Visibility (km)  \
Precip Type Summary
rain        Breezy                                320.000000         9.982000
            Breezy and Mostly Cloudy              280.000000         7.084000
            Breezy and Overcast                   246.333333         9.944433
            Breezy and Partly Cloudy              150.000000         9.982000
            Clear                                 160.071429        11.322517
            Foggy                                 180.684211         1.718463
            Humid and Mostly Cloudy                71.000000        11.125100
            Mostly Cloudy                         179.418605        11.139328
            Overcast                              194.909091         9.646095
            Partly Cloudy                         201.915254        12.001868
snow        Clear                                 131.500000        10.082625
            Foggy                                 174.384615         1.836638
            Mostly Cloudy                         180.500000        10.505250
            Overcast                              236.450000         6.120415
            Partly Cloudy                         168.571429         9.308100

                                      Pressure (millibars)
Precip Type Summary
rain        Breezy                                0.000000
            Breezy and Mostly Cloudy           1004.300000
            Breezy and Overcast                1007.250000
            Breezy and Partly Cloudy           1011.900000
            Clear                               969.584286
            Foggy                              1017.198421
            Humid and Mostly Cloudy            1010.030000
            Mostly Cloudy                      1016.423140
            Overcast                            999.215455
            Partly Cloudy                      1016.563390
snow        Clear                              1030.600000
            Foggy                              1025.837692
            Mostly Cloudy                      1027.515000
            Overcast                           1017.655500
            Partly Cloudy                      1023.934286

# b. Fill an intermittent time series to replace all missing dates with values of previous non-missing date.

# c. Perform appropriate year-month string to dates conversion.

In [10]:
from datetime import datetime

In [11]:
date_format = '%Y-%m-%d %H:%M:%S'
df["Formatted Date"]=df["Formatted Date"].apply(lambda x:datetime.strptime(x[:-10], date_format))

In [12]:
df['Formatted Date'].dtypes

dtype('<M8[ns]')

In [13]:
np.dtype('datetime64[ns]') == np.dtype('<M8[ns]')

True

# d. Split a dataset to group by two columns and then sort the aggregated results within the groups.

In [14]:
res=df.groupby(['Precip Type','Summary']).mean(numeric_only=1)['Humidity']
res

Precip Type  Summary
rain         Breezy                      0.600000
             Breezy and Mostly Cloudy    0.760000
             Breezy and Overcast         0.696667
             Breezy and Partly Cloudy    0.260000
             Clear                       0.753333
             Foggy                       0.960000
             Humid and Mostly Cloudy     0.870000
             Mostly Cloudy               0.719651
             Overcast                    0.838636
             Partly Cloudy               0.627119
snow         Clear                       0.867500
             Foggy                       0.928462
             Mostly Cloudy               0.850000
             Overcast                    0.888500
             Partly Cloudy               0.741429
Name: Humidity, dtype: float64

In [15]:
res.groupby(level=1).sum().sort_values()

Summary
Breezy and Partly Cloudy    0.260000
Breezy                      0.600000
Breezy and Overcast         0.696667
Breezy and Mostly Cloudy    0.760000
Humid and Mostly Cloudy     0.870000
Partly Cloudy               1.368547
Mostly Cloudy               1.569651
Clear                       1.620833
Overcast                    1.727136
Foggy                       1.888462
Name: Humidity, dtype: float64

In [16]:
res.groupby(level=0).sum().sort_values()

Precip Type
snow    4.275890
rain    7.085406
Name: Humidity, dtype: float64

# e.Split a given dataframe into groups with bin counts.

In [17]:
grp=df.groupby(['Precip Type',pd.cut(df['Visibility (km)'],5)])
grp.size().unstack()

Visibility (km),"(-0.0161, 3.22]","(3.22, 6.44]","(6.44, 9.66]","(9.66, 12.88]","(12.88, 16.1]"
Precip Type,,,,,
rain,20,39,24,156,99
snow,13,18,4,8,3